### ISSUE TITLE
感觉有个用户体验不好的地方

### ISSUE THREAD

**Issue by saucer-man** [gyyyy/ZoomEye-go#2]
当maxPage>5时，比如为10，则采用并发模式。

此时只要其中一页请求有问题，比如搜索结果只有7页，则访问第8页的时候出错，很可能就会没结果。（因为这时候往往第8页返回的最快）

我觉得程序的逻辑是不是可以更好：先访问第一页，看下结果有多少数量和用户有多少额度，然后根据这两个变量来调整maxPage，再进行余下的并发逻辑。

**Comment by gyyyy** [comment]
在MultiPageSearch处增加了对quota和total的判断，限制了maxPage的最大值。
